# yaml-language-server: $schema=https://goreleaser.com/static/schema-pro.json
version: 2

dist: tmp/dist

before: { hooks: ["go mod tidy"] }

builds:
  - env: ["CGO_ENABLED=0"] # disable cgo for static binaries
    flags: ["-trimpath"] # remove local fs paths from binary
    goos: ["darwin", "linux"]
    goarch: ["amd64", "arm64"]

# what to put in the tgz files
archives:
  - files: ["extra/", "LICENSE"]
    wrap_in_directory: true

# turn stuff off
announce: { skip: true }
changelog: { disable: true }

# brew tap
brews:
  - description: "Magically import/export CSVs from Google Sheets"
    homepage: https://github.com/gurgeous/gshoot
    repository: { owner: "gurgeous", name: "homebrew-tap" }
    test: system "#{bin}/gshoot --version"
    extra_install: |
      bash_completion.install "extra/gshoot.bash" => "gshoot"
      zsh_completion.install "extra/_gshoot" => "_gshoot"
