[env]
_.path = ["{{config_root}}/zig-out/bin", '{{config_root}}/bin']

[settings]
task.output = "quiet"

[tools]
gofumpt = "latest"
golang = "latest"

#
# tasks
#

[tasks]

# one-liners
build = "mkdir -p tmp && go build -o tmp/gshoot ./cmd/gshoot"
build-smoke = "mkdir -p tmp && go build -o tmp/smoke ./cmd/smoke"
lint = "go vet  ./... && mise _banner '✓ lint ✓'"
test = "go test ./... && mise _banner '✓ test ✓'"

check = """
mise lint ::: test ::: build
mise _banner -- "✓ check ✓"
"""

fmt = """
gofumpt -w $(find cmd internal -name '*.go')
if command -v gci >/dev/null 2>&1; then
  gci write -s standard -s default -s 'prefix(github.com/gurgeous/gshoot)' cmd internal
else
  mise _warning -- "skipping gci [not installed]"
fi
"""

init = """
if command -v gci >/dev/null 2>&1; then
  mise _banner -- "gci already installed"
else
  mise _banner -- "installing gci..."
  go install github.com/daixiang0/gci@latest
fi
mise _banner "✓ init ✓"
"""

smoke = """
mise build ::: build-smoke
./tmp/smoke
mise _banner "✓ smoke ✓"
"""


#
# banner and friends
#

[tasks._banner]
usage = 'flag "--bg <bg>" default="48;2;64;160;43" ; arg "<msg>"'
run = 'printf "\e[1;38;5;231;%sm[%s] %-72s\e[0m\n" "${usage_bg}" $(date +"%H:%M:%S") "${usage_msg}"'

[tasks._warning]
usage = 'arg "<msg>"'
run = 'mise _banner --bg "48;2;251;100;11" "$usage_msg"'

[tasks._fatal]
usage = 'arg "<msg>"'
run = 'mise _banner --bg "48;2;210;15;57" "$usage_msg" ; exit 1'
